frr defaults traditional
!
hostname censor2
!
interface eth1
 ip address 10.0.6.2/30
!
interface lo
 ip address 10.255.255.2/32
!
ip route 192.168.5.0/24 blackhole
!
router bgp 65902
 bgp router-id 92.92.92.92
 no bgp ebgp-requires-policy
 neighbor 10.0.6.1 remote-as 65003
 !
 address-family ipv4 unicast
  network 192.168.5.0/24
  neighbor 10.0.6.1 activate
 exit-address-family
!
!
