neighbor 10.0.6.1 {
    router-id 92.92.92.92;
    local-address 10.0.6.2;
    local-as 65902;
    peer-as 65003;
    hold-time 180;
    
    family {
        ipv4 unicast;
    }
    
    static {
        route 192.168.5.0/24 next-hop 10.0.6.2;
    }
}
