neighbor 10.0.5.1 {
    router-id 91.91.91.91;
    local-address 10.0.5.2;
    local-as 65901;
    peer-as 65002;
    hold-time 180;
    
    family {
        ipv4 unicast;
    }
    
    static {
        route 192.168.1.0/25 next-hop 10.0.5.2;
    }
}
