frr defaults traditional
!
hostname router1
!
rpki
 rpki polling_period 10
 rpki cache rpki-validator 3323 preference 1
 exit
!
interface eth1
 ip address 10.0.0.1/30
!
interface eth2
 ip address 10.0.2.1/30
!
interface lo
 ip address 192.168.1.1/24
!
route-map RM-RPKI-IN deny 10
 match rpki invalid
!
route-map RM-RPKI-IN permit 20
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.0.0.2 remote-as 65002
 neighbor 10.0.2.2 remote-as 65901
 !
 address-family ipv4 unicast
  network 192.168.1.0/24
  neighbor 10.0.0.2 activate
  neighbor 10.0.2.2 activate
  neighbor 10.0.0.2 route-map RM-RPKI-IN in
  neighbor 10.0.2.2 route-map RM-RPKI-IN in
 exit-address-family
!
!
