frr defaults traditional
!
hostname AS3
!
interface eth1
 ip address 10.0.1.2/30
!
interface eth2
 ip address 10.0.2.2/30
!
interface eth3
 ip address 10.0.6.2/30
!
interface eth4
 ip address 10.0.8.2/30
!
interface eth5
 ip address 10.0.12.2/30
!
interface eth6
 ip address 10.0.14.2/30
!
interface lo
 ip address 192.168.3.1/24
!
ip prefix-list PFX-CONE seq 5 permit 192.168.3.0/24
 ip prefix-list PFX-CONE seq 10 permit 192.168.12.0/24
 ip prefix-list PFX-CONE seq 15 permit 192.168.13.0/24
 ip prefix-list PFX-CONE seq 20 permit 192.168.14.0/24
 ip prefix-list PFX-CONE seq 25 permit 192.168.15.0/24
 ip prefix-list PFX-CONE seq 30 permit 192.168.16.0/24
 ip prefix-list PFX-CONE seq 35 permit 192.168.18.0/24
 ip prefix-list PFX-CONE seq 40 permit 192.168.19.0/24
 ip prefix-list PFX-CONE seq 45 permit 192.168.20.0/24
 ip prefix-list PFX-CONE seq 50 permit 192.168.21.0/24
 ip prefix-list PFX-CONE seq 55 permit 192.168.22.0/24
 ip prefix-list PFX-CONE seq 60 permit 192.168.26.0/24
 ip prefix-list PFX-CONE seq 65 permit 192.168.27.0/24
 ip prefix-list PFX-CONE seq 70 permit 192.168.29.0/24
 ip prefix-list PFX-CONE seq 75 permit 192.168.30.0/24
 ip prefix-list PFX-CONE seq 80 permit 192.168.5.0/24
 ip prefix-list PFX-CONE seq 85 permit 192.168.6.0/24
 ip prefix-list PFX-CONE seq 90 permit 192.168.8.0/24
 ip prefix-list PFX-CONE seq 95 permit 192.168.9.0/24
!
ip community-list standard CL-NON-CUSTOMER permit 65000:200
ip community-list standard CL-NON-CUSTOMER permit 65000:300
ip community-list standard CL-CUSTOMER permit 65000:100
!
route-map RM-ORIGIN-CUSTOMER permit 10
 set community 65000:100 additive
!
route-map RM-IN-AS8 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS6 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS5 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS9 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS2 permit 20
 set local-preference 100
 set community 65000:200 additive
!
route-map RM-IN-CENSOR1 permit 20
 set local-preference 100
 set community 65000:200 additive
!
!
route-map RM-OUT-AS2 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-AS2 deny 20
!
route-map RM-OUT-CENSOR1 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-CENSOR1 deny 20
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65901
 neighbor 10.0.2.1 remote-as 65002
 neighbor 10.0.6.1 remote-as 65005
 neighbor 10.0.8.1 remote-as 65006
 neighbor 10.0.12.1 remote-as 65008
 neighbor 10.0.14.1 remote-as 65009
 !
 address-family ipv4 unicast
  network 192.168.3.0/24 route-map RM-ORIGIN-CUSTOMER
  neighbor 10.0.1.1 activate
  neighbor 10.0.1.1 send-community both
  neighbor 10.0.2.1 activate
  neighbor 10.0.2.1 send-community both
  neighbor 10.0.6.1 activate
  neighbor 10.0.6.1 send-community both
  neighbor 10.0.8.1 activate
  neighbor 10.0.8.1 send-community both
  neighbor 10.0.12.1 activate
  neighbor 10.0.12.1 send-community both
  neighbor 10.0.14.1 activate
  neighbor 10.0.14.1 send-community both
  neighbor 10.0.12.1 route-map RM-IN-AS8 in
  neighbor 10.0.8.1 route-map RM-IN-AS6 in
  neighbor 10.0.6.1 route-map RM-IN-AS5 in
  neighbor 10.0.14.1 route-map RM-IN-AS9 in
  neighbor 10.0.2.1 route-map RM-IN-AS2 in
  neighbor 10.0.1.1 route-map RM-IN-CENSOR1 in
  neighbor 10.0.2.1 route-map RM-OUT-AS2 out
  neighbor 10.0.1.1 route-map RM-OUT-CENSOR1 out
 exit-address-family
!
!
