frr defaults traditional
!
hostname router4
!
interface eth1
 ip address 10.0.3.2/30
!
interface eth2
 ip address 10.0.4.2/30
!
interface eth3
 ip address 10.0.7.1/30
!
interface eth4
 ip address 10.0.9.1/30
!
interface lo
 ip address 192.168.4.1/24
!
router bgp 65004
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.0.3.1 remote-as 65002
 neighbor 10.0.4.1 remote-as 65003
 neighbor 10.0.7.2 remote-as 65005
 neighbor 10.0.9.2 remote-as 65006
 !
 address-family ipv4 unicast
  network 192.168.4.0/24
  neighbor 10.0.3.1 activate
  neighbor 10.0.4.1 activate
  neighbor 10.0.7.2 activate
  neighbor 10.0.9.2 activate
 exit-address-family
!
!
