frr defaults traditional
!
hostname AS4
!
interface eth1
 ip address 10.0.3.1/30
!
interface eth2
 ip address 10.0.4.1/30
!
interface eth3
 ip address 10.0.17.1/30
!
interface eth4
 ip address 10.0.18.1/30
!
interface eth5
 ip address 10.0.24.2/30
!
interface eth6
 ip address 10.0.25.2/30
!
interface eth7
 ip address 10.0.44.2/30
!
interface lo
 ip address 192.168.4.1/24
!
ip prefix-list PFX-CONE seq 5 permit 192.168.4.0/24
 ip prefix-list PFX-CONE seq 10 permit 192.168.11.0/24
 ip prefix-list PFX-CONE seq 15 permit 192.168.12.0/24
 ip prefix-list PFX-CONE seq 20 permit 192.168.25.0/24
!
ip community-list standard CL-NON-CUSTOMER permit 65000:200
ip community-list standard CL-NON-CUSTOMER permit 65000:300
ip community-list standard CL-CUSTOMER permit 65000:100
!
route-map RM-ORIGIN-CUSTOMER permit 10
 set community 65000:100 additive
!
route-map RM-IN-AS11 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS12 permit 20
 set local-preference 200
 set community 65000:100 additive
!
route-map RM-IN-AS9 permit 20
 set local-preference 100
 set community 65000:200 additive
!
route-map RM-IN-AS2 permit 20
 set local-preference 50
 set community 65000:300 additive
!
route-map RM-IN-AS10 permit 20
 set local-preference 100
 set community 65000:200 additive
!
route-map RM-IN-CENSOR1 permit 20
 set local-preference 50
 set community 65000:300 additive
!
route-map RM-IN-AS25 permit 20
 set local-preference 200
 set community 65000:100 additive
!
!
route-map RM-OUT-AS9 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-AS9 deny 20
!
route-map RM-OUT-AS2 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-AS2 deny 20
!
route-map RM-OUT-AS10 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-AS10 deny 20
!
route-map RM-OUT-CENSOR1 permit 10
 match ip address prefix-list PFX-CONE
!
route-map RM-OUT-CENSOR1 deny 20
!
router bgp 65004
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.0.3.2 remote-as 65901
 neighbor 10.0.4.2 remote-as 65002
 neighbor 10.0.17.2 remote-as 65009
 neighbor 10.0.18.2 remote-as 65010
 neighbor 10.0.24.1 remote-as 65011
 neighbor 10.0.25.1 remote-as 65012
 neighbor 10.0.44.1 remote-as 65025
 !
 address-family ipv4 unicast
  network 192.168.4.0/24 route-map RM-ORIGIN-CUSTOMER
  neighbor 10.0.3.2 activate
  neighbor 10.0.3.2 send-community both
  neighbor 10.0.4.2 activate
  neighbor 10.0.4.2 send-community both
  neighbor 10.0.17.2 activate
  neighbor 10.0.17.2 send-community both
  neighbor 10.0.18.2 activate
  neighbor 10.0.18.2 send-community both
  neighbor 10.0.24.1 activate
  neighbor 10.0.24.1 send-community both
  neighbor 10.0.25.1 activate
  neighbor 10.0.25.1 send-community both
  neighbor 10.0.44.1 activate
  neighbor 10.0.44.1 send-community both
  neighbor 10.0.24.1 route-map RM-IN-AS11 in
  neighbor 10.0.25.1 route-map RM-IN-AS12 in
  neighbor 10.0.17.2 route-map RM-IN-AS9 in
  neighbor 10.0.4.2 route-map RM-IN-AS2 in
  neighbor 10.0.18.2 route-map RM-IN-AS10 in
  neighbor 10.0.3.2 route-map RM-IN-CENSOR1 in
  neighbor 10.0.44.1 route-map RM-IN-AS25 in
  neighbor 10.0.17.2 route-map RM-OUT-AS9 out
  neighbor 10.0.4.2 route-map RM-OUT-AS2 out
  neighbor 10.0.18.2 route-map RM-OUT-AS10 out
  neighbor 10.0.3.2 route-map RM-OUT-CENSOR1 out
 exit-address-family
!
!
