frr defaults traditional
!
hostname router5
!
interface eth1
 ip address 10.0.7.2/30
!
interface lo
 ip address 192.168.5.1/24
!
router bgp 65005
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 neighbor 10.0.7.1 remote-as 65004
 !
 address-family ipv4 unicast
  network 192.168.5.0/24
  neighbor 10.0.7.1 activate
 exit-address-family
!
!
