
# BGP Neighbor zu Router2 (AS 65002)
neighbor 10.0.5.1 {
    router-id 99.99.99.99;
    local-address 10.0.5.2;
    local-as 65999;
    peer-as 65002;
    hold-time 180;
    
    family {
        ipv4 unicast;
    }
    #sub-prefix hijacking
    static {
        route 192.168.1.0/25 next-hop 10.0.5.2;
    }
}
