global:
  config:
    as: 65004
    router-id: 4.4.4.4

neighbors:
  - config:
      neighbor-address: 10.0.3.1
      peer-as: 65002
    transport:
      config:
        local-address: 10.0.3.2
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast
  - config:
      neighbor-address: 10.0.4.1
      peer-as: 65003
    transport:
      config:
        local-address: 10.0.4.2
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast

defined-sets:
  prefix-sets:
    - prefix-set-name: local-network
      prefix-list:
        - ip-prefix: 192.168.4.0/24

policy-definitions:
  - name: export-local
    statements:
      - conditions:
          match-prefix-set:
            prefix-set: local-network
        actions:
          route-disposition: accept-route
