global:
  config:
    as: 65003
    router-id: 3.3.3.3

neighbors:
  - config:
      neighbor-address: 10.0.1.1
      peer-as: 65001
    transport:
      config:
        local-address: 10.0.1.2
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast
  - config:
      neighbor-address: 10.0.2.1
      peer-as: 65002
    transport:
      config:
        local-address: 10.0.2.2
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast
  - config:
      neighbor-address: 10.0.4.2
      peer-as: 65004
    transport:
      config:
        local-address: 10.0.4.1
    afi-safis:
      - config:
          afi-safi-name: ipv4-unicast

defined-sets:
  prefix-sets:
    - prefix-set-name: local-network
      prefix-list:
        - ip-prefix: 192.168.3.0/24

policy-definitions:
  - name: export-local
    statements:
      - conditions:
          match-prefix-set:
            prefix-set: local-network
        actions:
          route-disposition: accept-route
